site_name: Jump & Survive Documentation
theme:
  name: mkdocs
  user_color_mode_toggle: true
  navigation_depth: 3
  locale: id_ID
nav:
  - Beranda: index.md
  - Teknis Pengembangan: 
    - Ikhtisar: development/index.md
  - Cara Menjalankan Program: usage.md
  - Cara Memainkan: how-to-play.md
