site_name: Jump & Survive Documentation
theme:
  name: material
  icon:
    logo: material/book-open-blank-variant-outline
  favicon: favicon.ico
  palette:
    - scheme: default # Palette toggle for light mode
      primary: orange
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate # Palette toggle for dark mode
      primary: amber
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.expand
nav:
  - Beranda: index.md
  - Teknis Pengembangan:
      - Ikhtisar: development/index.md
      - Struktur Kode: development/code-structure.md
      - Penjelasan Modul-modul: development/modules.md
  - Penggunaan:
      - Cara Menjalankan Program: usage.md
      - Cara Memainkan: how-to-play.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
