site_name: Jump & Survive Documentation
theme:
  name: material
  icon:
    logo: material/book-open-blank-variant-outline
  favicon: favicon.ico
  palette:
    - scheme: default # Palette toggle for light mode
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate # Palette toggle for dark mode
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Beranda: index.md
  - Teknis Pengembangan:
      - Gambaran Umum: development/index.md
      - Struktur Kode: development/code-structure.md
      - Penjelasan Modul-modul:
          - Daftar Modul: development/modules/index.md
          - Main Program: development/modules/main.md
          - Modul game: development/modules/game.md
          - Modul game_state: development/modules/game_state.md
          - Modul transform: development/modules/transform.md
          - Modul vector: development/modules/vector.md
          - Modul entity: development/modules/entity.md
          - Modul physics: development/modules/physics.md
          - Modul player: development/modules/player.md
          - Modul level: development/modules/level.md
          - Modul obstacle: development/modules/obstacle.md
          - Modul game_stat: development/modules/game_stat.md
          - Modul UI: development/modules/ui.md
          - Modul SFX: development/modules/sfx.md
          - Modul util: development/modules/util.md
          - Start Menu (menu_state): development/modules/menu_state.md
          - Stage 0 (stage0_state): development/modules/stage0_state.md
          - Stage 1 (stage1_state): development/modules/stage1_state.md
  - Penggunaan:
      - Cara Menjalankan Program: usage.md
      - Cara Memainkan: how-to-play.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
